module2-task1 "Нужно больше функций"
htmlacademy-javascript/2344405-kekstagram-28 pull request #2
Opened 2023-03-02 10:40 UTC by ivanMazalov

Все работают, однако ни в одном не смог осилить доп. задания

2023-03-02 14:30 UTC, blckwltz requested changes
@ivanMazalov все хорошо, но не хватает последней функции из задания

2023-03-02 14:30 UTC, blckwltz commented on js/functions.js
> +    if (str.toLowerCase() === downStr.split('').reverse().join('')) {
@ivanMazalov здесь можно заменить на `downStr === downStr.split('').reverse().join('')`, чтобы не выполнять 2 раза приведение к нижнему регистру

2023-03-02 14:30 UTC, blckwltz commented on package-lock.json
> -        "npm": "8.x"
@ivanMazalov эти строчки хорошо бы вернуть обратно)

2023-03-02 14:30 UTC, blckwltz commented on js/functions.js
> +if (extResult === Number(extResult)){
@ivanMazalov тут можно использовать такую проверку `if (Number.isInteger(extResult))`

2023-03-03 09:41 UTC, ivanMazalov reviewed
Исправил. параллельно пытаюсь разобраться с Гитхабом. Если этот комментарий  прочтен в нужном месте (пулреквесте) - значит я правильно сделал  :)

2023-03-03 16:54 UTC, merged